// <auto-generated />
using System;
using Hospital.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240517045234_SeedData data")]
    partial class SeedDatadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9849),
                            DateTime = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9850),
                            DoctorId = 1L,
                            IsDeleted = false,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9851),
                            DateTime = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9851),
                            DoctorId = 2L,
                            IsDeleted = false,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9852),
                            DateTime = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9852),
                            DoctorId = 3L,
                            IsDeleted = false,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9828),
                            Email = "email@gmail.com",
                            FirstName = "Umidjon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9832),
                            Email = "email@gmail.com",
                            FirstName = "Odiljon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9833),
                            Email = "email@gmail.com",
                            FirstName = "Valijon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9868),
                            DateTime = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9871),
                            DoctorId = 1L,
                            IsDeleted = false,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9871),
                            DateTime = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9872),
                            DoctorId = 3L,
                            IsDeleted = false,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<string>("MedicineUsage")
                        .HasColumnType("text");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9891),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "Dori",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9893),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "sdsds",
                            MedicineUsage = "sdsd",
                            PrescriptionId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9894),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "Dori",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9895),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "DoriDarmon",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9675),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9679),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9680),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9681),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.UserContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserContacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Andijon Shahri",
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9802),
                            IsDeleted = false,
                            Phone = "+9989901233567",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Qarshi Shahri",
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9805),
                            IsDeleted = false,
                            Phone = "+9989901234567",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Toshkent Shahri",
                            CreatedAt = new DateTime(2024, 5, 17, 4, 52, 33, 323, DateTimeKind.Utc).AddTicks(9813),
                            IsDeleted = false,
                            Phone = "+9989901234567",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.UserContact", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithOne("Contact")
                        .HasForeignKey("Hospital.Domain.Entities.UserContact", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Contact");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
