// <auto-generated />
using System;
using Hospital.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240601093259_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(324),
                            DateTime = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(325),
                            DoctorId = 1L,
                            IsDeleted = false,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(326),
                            DateTime = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(327),
                            DoctorId = 2L,
                            IsDeleted = false,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(328),
                            DateTime = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(328),
                            DoctorId = 3L,
                            IsDeleted = false,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(300),
                            Email = "email@gmail.com",
                            FirstName = "Umidjon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(303),
                            Email = "email@gmail.com",
                            FirstName = "Odiljon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(305),
                            Email = "email@gmail.com",
                            FirstName = "Valijon",
                            IsDeleted = false,
                            LastName = "Maxammadsoliyev",
                            Password = "Password",
                            Position = "Dentist"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(345),
                            DateTime = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(347),
                            DoctorId = 1L,
                            IsDeleted = false,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(349),
                            DateTime = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(349),
                            DoctorId = 3L,
                            IsDeleted = false,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<string>("MedicineUsage")
                        .HasColumnType("text");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(366),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "Dori",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(369),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "sdsds",
                            MedicineUsage = "sdsd",
                            PrescriptionId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(370),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "Dori",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(371),
                            Days = 11,
                            IsDeleted = false,
                            MedicineName = "DoriDarmon",
                            MedicineUsage = "Ichiladi",
                            PrescriptionId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(82),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(87),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(88),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(90),
                            Email = "Valijonov@gmail.com",
                            FirstName = "Ali",
                            IsDeleted = false,
                            LastName = "Valiyev",
                            Password = "Password"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.UserContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserContacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Andijon Shahri",
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(276),
                            IsDeleted = false,
                            Phone = "+9989901233567",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Qarshi Shahri",
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(279),
                            IsDeleted = false,
                            Phone = "+9989901234567",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Toshkent Shahri",
                            CreatedAt = new DateTime(2024, 6, 1, 9, 32, 59, 9, DateTimeKind.Utc).AddTicks(280),
                            IsDeleted = false,
                            Phone = "+9989901234567",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.UserContact", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.User", "User")
                        .WithOne("Contact")
                        .HasForeignKey("Hospital.Domain.Entities.UserContact", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Contact");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
